import { Artist, Track } from '@/types'

interface DevCardProps {
  data: (Artist | Track)[]
  type: 'artists' | 'tracks'
  userName: string
}

export default function DevCard({ data, type, userName }: DevCardProps) {
  return (
    <div className="w-[340px] h-[500px] bg-[#1E1E1E] p-6 rounded-lg font-mono text-sm shadow-2xl overflow-hidden relative">
      <div className="flex gap-2 mb-4">
        <div className="w-3 h-3 rounded-full bg-[#FF5F56]" />
        <div className="w-3 h-3 rounded-full bg-[#FFBD2E]" />
        <div className="w-3 h-3 rounded-full bg-[#27C93F]" />
      </div>

      <div className="text-[#569CD6] mb-2">
        class <span className="text-[#4EC9B0]">UserStats</span> {'{'}
      </div>

      <div className="pl-4">
        <div className="text-[#9CDCFE] mb-1">
          user = <span className="text-[#CE9178]">&quot;{userName}&quot;</span>;
        </div>
        <div className="text-[#9CDCFE] mb-1">
          category = <span className="text-[#CE9178]">&quot;Top {type}&quot;</span>;
        </div>

        <div className="text-[#DCDCAA] mt-4 mb-1">getFavorites() {'{'}</div>
        <div className="pl-4 text-[#C586C0]">
          return <span className="text-[#D4D4D4]">[</span>
        </div>

        <div className="pl-8 flex flex-col gap-1">
          {data.slice(0, 10).map((item, i) => (
            <div key={item.id} className="text-[#CE9178] truncate">
              &quot;{item.name}&quot;<span className="text-[#D4D4D4]">{i < 9 ? ',' : ''}</span>
            </div>
          ))}
        </div>

        <div className="pl-4 text-[#D4D4D4]">]</div>
        <div className="text-[#DCDCAA] mb-1">{'}'}</div>
      </div>

      <div className="text-[#D4D4D4] mt-2">{'}'}</div>

      <div className="absolute bottom-4 right-4 opacity-50 text-[10px] text-gray-500">
        generated by tobi
      </div>
    </div>
  )
}
